include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    # Added by Marcos
    avoid_print: false
    prefer_single_quotes: false
    prefer_const_constructors_in_immutables: false
    prefer_typing_uninitialized_variables: false
    use_key_in_widget_constructors: false
    prefer_final_fields: false
    depend_on_referenced_packages: false
    use_build_context_synchronously: false
    slash_for_doc_comments: false
    no_leading_underscores_for_local_identifiers: false
    avoid_web_libraries_in_flutter: false
    # unused_local_variable: false
